repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.78.0
    hooks:
      - id: terraform_fmt
        args: [
          --args=-recursive
          ]
      - id: terraform_tfsec
      - id: terraform_docs
      - id: terraform_tflint
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: '2.3.212'
    hooks:
    - id: checkov
      verbose: true
      args:
        - '--download-external-modules'
        - 'sebastianczech/infra-k8s-oracle-cloud/oci:0.0.7'
        - '--compact'
        - '--quiet'
        - '--soft-fail'
  - repo: https://github.com/tenable/terrascan
    rev: v1.18.1
    hooks:
      - id: terraform-pre-commit
        args: [ '-i terraform' ]