repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.74.2 # version from https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_fmt
        args: [
          --args=-check,
          --args=-recursive
          ]
      - id: terraform_tfsec
      - id: terraform_docs
      - id: terraform_tflint
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: '2.1.192' # version from https://github.com/bridgecrewio/checkov/releases
    hooks:
    - id: checkov
      verbose: true
      args: 
        - '--download-external-modules'
        - 'sebastianczech/infra-k8s-oracle-cloud/oci:0.0.7'
        - '--compact'
        - '--quiet'
        - '--soft-fail'
        